# Generated by Django 6.0.3 on 2026-03-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
